#!/bin/bash

# ┌────────────────────────────────────┐
# │                                    │
# │               WIDTHS               │
# │                                    │
# └────────────────────────────────────┘

printf "\n${TEXT_EMERALD_500}WIDTHS & LINES:${RESET}\n"

printf "\n${TEXT_PINK_500}W_FULL:${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_FULL $TEXT_EMERALD_300$ICON_DH

printf "\n${TEXT_PINK_500}W_1_2: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_1_2 $TEXT_AMBER_300$ICON_FH

printf "\n${TEXT_PINK_500}W_2_3: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_2_3 $TEXT_SKY_300$ICON_WH

printf "\n${TEXT_PINK_500}W_1_3: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_1_3 $TEXT_SKY_300$ICON_WH

printf "\n${TEXT_PINK_500}W_3_4: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_3_4 $TEXT_PINK_300$ICON_WH_DASH

printf "\n${TEXT_PINK_500}W_2_4: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_2_4 $TEXT_PINK_300$ICON_WH_DASH

printf "\n${TEXT_PINK_500}W_1_4: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_1_4 $TEXT_PINK_300$ICON_WH_DASH

printf "\n${TEXT_PINK_500}W_4_5: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_4_5 $TEXT_LIME_300$ICON_WH_DASH

printf "\n${TEXT_PINK_500}W_3_5: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_3_5 $TEXT_LIME_300$ICON_WH_DASH

printf "\n${TEXT_PINK_500}W_2_5: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_2_5 $TEXT_LIME_300$ICON_WH_DASH

printf "\n${TEXT_PINK_500}W_1_5: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_1_5 $TEXT_LIME_300$ICON_WH_DASH

printf "\n${TEXT_PINK_500}W_5_6: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_5_6 $TEXT_VIOLET_300$ICON_WH_DOTS

printf "\n${TEXT_PINK_500}W_4_6: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_4_6 $TEXT_VIOLET_300$ICON_WH_DOTS

printf "\n${TEXT_PINK_500}W_3_6: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_3_6 $TEXT_VIOLET_300$ICON_WH_DOTS

printf "\n${TEXT_PINK_500}W_2_6: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_2_6 $TEXT_VIOLET_300$ICON_WH_DOTS

printf "\n${TEXT_PINK_500}W_1_6: ${RESET}\n"
$SPINNAKER_COMPONENTS_FOLDER/line.sh $W_1_6 $TEXT_VIOLET_300$ICON_WH_DOTS
printf '\n'
